sudo: required

language:

services:
  - docker

before_install:
  - docker build -t ss/homeguide .

script:
  - docker run ss/homeguide npm test -- --coverage


deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "us-west-1"  
  app: "homeadvisor"
  env: "Homeadvisor-env"
  bucket_name: "elasticbeanstalk-us-west-1-541635236411"
